// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0--rc2
// source: proto/monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_InstallAgent_FullMethodName          = "/monitor.MonitorService/InstallAgent"
	MonitorService_GetSystemInfo_FullMethodName         = "/monitor.MonitorService/GetSystemInfo"
	MonitorService_GetLastSystemInfo_FullMethodName     = "/monitor.MonitorService/GetLastSystemInfo"
	MonitorService_ListAgents_FullMethodName            = "/monitor.MonitorService/ListAgents"
	MonitorService_CheckServerStatus_FullMethodName     = "/monitor.MonitorService/CheckServerStatus"
	MonitorService_GetHostLastUpdateTime_FullMethodName = "/monitor.MonitorService/GetHostLastUpdateTime"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 系统信息采集服务
type MonitorServiceClient interface {
	// 安装agent
	InstallAgent(ctx context.Context, in *InstallAgentRequest, opts ...grpc.CallOption) (*InstallAgentResponse, error)
	// 获取系统信息
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error)
	// 获取最新的系统信息
	GetLastSystemInfo(ctx context.Context, in *GetLastSystemInfoRequest, opts ...grpc.CallOption) (*GetLastSystemInfoResponse, error)
	// 获取agent列表
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// 检查服务器状态
	CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error)
	// 获取主机最后更新时间
	GetHostLastUpdateTime(ctx context.Context, in *GetHostLastUpdateTimeRequest, opts ...grpc.CallOption) (*GetHostLastUpdateTimeResponse, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) InstallAgent(ctx context.Context, in *InstallAgentRequest, opts ...grpc.CallOption) (*InstallAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallAgentResponse)
	err := c.cc.Invoke(ctx, MonitorService_InstallAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetLastSystemInfo(ctx context.Context, in *GetLastSystemInfoRequest, opts ...grpc.CallOption) (*GetLastSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastSystemInfoResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetLastSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckServerStatusResponse)
	err := c.cc.Invoke(ctx, MonitorService_CheckServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetHostLastUpdateTime(ctx context.Context, in *GetHostLastUpdateTimeRequest, opts ...grpc.CallOption) (*GetHostLastUpdateTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostLastUpdateTimeResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetHostLastUpdateTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
//
// 系统信息采集服务
type MonitorServiceServer interface {
	// 安装agent
	InstallAgent(context.Context, *InstallAgentRequest) (*InstallAgentResponse, error)
	// 获取系统信息
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error)
	// 获取最新的系统信息
	GetLastSystemInfo(context.Context, *GetLastSystemInfoRequest) (*GetLastSystemInfoResponse, error)
	// 获取agent列表
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// 检查服务器状态
	CheckServerStatus(context.Context, *CheckServerStatusRequest) (*CheckServerStatusResponse, error)
	// 获取主机最后更新时间
	GetHostLastUpdateTime(context.Context, *GetHostLastUpdateTimeRequest) (*GetHostLastUpdateTimeResponse, error)
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) InstallAgent(context.Context, *InstallAgentRequest) (*InstallAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallAgent not implemented")
}
func (UnimplementedMonitorServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*GetSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedMonitorServiceServer) GetLastSystemInfo(context.Context, *GetLastSystemInfoRequest) (*GetLastSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastSystemInfo not implemented")
}
func (UnimplementedMonitorServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedMonitorServiceServer) CheckServerStatus(context.Context, *CheckServerStatusRequest) (*CheckServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerStatus not implemented")
}
func (UnimplementedMonitorServiceServer) GetHostLastUpdateTime(context.Context, *GetHostLastUpdateTimeRequest) (*GetHostLastUpdateTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostLastUpdateTime not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_InstallAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).InstallAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_InstallAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).InstallAgent(ctx, req.(*InstallAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetLastSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetLastSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetLastSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetLastSystemInfo(ctx, req.(*GetLastSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_CheckServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).CheckServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_CheckServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).CheckServerStatus(ctx, req.(*CheckServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetHostLastUpdateTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostLastUpdateTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetHostLastUpdateTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetHostLastUpdateTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetHostLastUpdateTime(ctx, req.(*GetHostLastUpdateTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallAgent",
			Handler:    _MonitorService_InstallAgent_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _MonitorService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetLastSystemInfo",
			Handler:    _MonitorService_GetLastSystemInfo_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _MonitorService_ListAgents_Handler,
		},
		{
			MethodName: "CheckServerStatus",
			Handler:    _MonitorService_CheckServerStatus_Handler,
		},
		{
			MethodName: "GetHostLastUpdateTime",
			Handler:    _MonitorService_GetHostLastUpdateTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monitor.proto",
}
