// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/monitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 安装agent请求
type InstallAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	HostName      string                 `protobuf:"bytes,5,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Os            string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	KernelArch    string                 `protobuf:"bytes,8,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	Token         string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAgentRequest) Reset() {
	*x = InstallAgentRequest{}
	mi := &file_proto_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAgentRequest) ProtoMessage() {}

func (x *InstallAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAgentRequest.ProtoReflect.Descriptor instead.
func (*InstallAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *InstallAgentRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InstallAgentRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *InstallAgentRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InstallAgentRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InstallAgentRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *InstallAgentRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InstallAgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *InstallAgentRequest) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *InstallAgentRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 安装agent响应
type InstallAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAgentResponse) Reset() {
	*x = InstallAgentResponse{}
	mi := &file_proto_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAgentResponse) ProtoMessage() {}

func (x *InstallAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAgentResponse.ProtoReflect.Descriptor instead.
func (*InstallAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *InstallAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallAgentResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取系统信息请求
type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_proto_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *GetSystemInfoRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetSystemInfoRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetSystemInfoRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// 获取系统信息响应
type GetSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SystemInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_proto_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *GetSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 获取最新系统信息请求
type GetLastSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSystemInfoRequest) Reset() {
	*x = GetLastSystemInfoRequest{}
	mi := &file_proto_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSystemInfoRequest) ProtoMessage() {}

func (x *GetLastSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLastSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastSystemInfoRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// 获取最新系统信息响应
type GetLastSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SystemInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSystemInfoResponse) Reset() {
	*x = GetLastSystemInfoResponse{}
	mi := &file_proto_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSystemInfoResponse) ProtoMessage() {}

func (x *GetLastSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLastSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetLastSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 获取agent列表请求
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{6}
}

// 获取agent列表响应
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// 检查服务器状态请求
type CheckServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerStatusRequest) Reset() {
	*x = CheckServerStatusRequest{}
	mi := &file_proto_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerStatusRequest) ProtoMessage() {}

func (x *CheckServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *CheckServerStatusRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// 检查服务器状态响应
type CheckServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,2,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerStatusResponse) Reset() {
	*x = CheckServerStatusResponse{}
	mi := &file_proto_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerStatusResponse) ProtoMessage() {}

func (x *CheckServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *CheckServerStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *CheckServerStatusResponse) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

// 系统信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostInfo      *HostInfo              `protobuf:"bytes,1,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	CpuInfo       []*CPUInfo             `protobuf:"bytes,2,rep,name=cpu_info,json=cpuInfo,proto3" json:"cpu_info,omitempty"`
	MemoryInfo    *MemoryInfo            `protobuf:"bytes,3,opt,name=memory_info,json=memoryInfo,proto3" json:"memory_info,omitempty"`
	ProcessInfo   []*ProcessInfo         `protobuf:"bytes,4,rep,name=process_info,json=processInfo,proto3" json:"process_info,omitempty"`
	NetworkInfo   []*NetworkInfo         `protobuf:"bytes,5,rep,name=network_info,json=networkInfo,proto3" json:"network_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *SystemInfo) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *SystemInfo) GetCpuInfo() []*CPUInfo {
	if x != nil {
		return x.CpuInfo
	}
	return nil
}

func (x *SystemInfo) GetMemoryInfo() *MemoryInfo {
	if x != nil {
		return x.MemoryInfo
	}
	return nil
}

func (x *SystemInfo) GetProcessInfo() []*ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

func (x *SystemInfo) GetNetworkInfo() []*NetworkInfo {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

// 主机信息
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	KernelArch    string                 `protobuf:"bytes,5,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *HostInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HostInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *HostInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// CPU信息
type CPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	CoresNum      int32                  `protobuf:"varint,3,opt,name=cores_num,json=coresNum,proto3" json:"cores_num,omitempty"`
	Percent       float64                `protobuf:"fixed64,4,opt,name=percent,proto3" json:"percent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_proto_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *CPUInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CPUInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CPUInfo) GetCoresNum() int32 {
	if x != nil {
		return x.CoresNum
	}
	return 0
}

func (x *CPUInfo) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *CPUInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 内存信息
type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Total         string                 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	Available     string                 `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	Used          string                 `protobuf:"bytes,4,opt,name=used,proto3" json:"used,omitempty"`
	Free          string                 `protobuf:"bytes,5,opt,name=free,proto3" json:"free,omitempty"`
	UserPercent   float64                `protobuf:"fixed64,6,opt,name=user_percent,json=userPercent,proto3" json:"user_percent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_proto_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *MemoryInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemoryInfo) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *MemoryInfo) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *MemoryInfo) GetUsed() string {
	if x != nil {
		return x.Used
	}
	return ""
}

func (x *MemoryInfo) GetFree() string {
	if x != nil {
		return x.Free
	}
	return ""
}

func (x *MemoryInfo) GetUserPercent() float64 {
	if x != nil {
		return x.UserPercent
	}
	return 0
}

func (x *MemoryInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 进程信息
type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,4,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_monitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 网络信息
type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_proto_monitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInfo) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetworkInfo) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Agent信息
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	KernelArch    string                 `protobuf:"bytes,4,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_monitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{16}
}

func (x *AgentInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

var File_proto_monitor_proto protoreflect.FileDescriptor

const file_proto_monitor_proto_rawDesc = "" +
	"\n" +
	"\x13proto/monitor.proto\x12\amonitor\"\xed\x01\n" +
	"\x13InstallAgentRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1b\n" +
	"\thost_name\x18\x05 \x01(\tR\bhostName\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12\x1f\n" +
	"\vkernel_arch\x18\b \x01(\tR\n" +
	"kernelArch\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\"`\n" +
	"\x14InstallAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"V\n" +
	"\x14GetSystemInfoRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"@\n" +
	"\x15GetSystemInfoResponse\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.monitor.SystemInfoR\x04info\"6\n" +
	"\x18GetLastSystemInfoRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"D\n" +
	"\x19GetLastSystemInfoResponse\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.monitor.SystemInfoR\x04info\"\x13\n" +
	"\x11ListAgentsRequest\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.monitor.AgentInfoR\x06agents\"6\n" +
	"\x18CheckServerStatusRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"Z\n" +
	"\x19CheckServerStatusResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12%\n" +
	"\x0elast_heartbeat\x18\x02 \x01(\tR\rlastHeartbeat\"\x91\x02\n" +
	"\n" +
	"SystemInfo\x12.\n" +
	"\thost_info\x18\x01 \x01(\v2\x11.monitor.HostInfoR\bhostInfo\x12+\n" +
	"\bcpu_info\x18\x02 \x03(\v2\x10.monitor.CPUInfoR\acpuInfo\x124\n" +
	"\vmemory_info\x18\x03 \x01(\v2\x13.monitor.MemoryInfoR\n" +
	"memoryInfo\x127\n" +
	"\fprocess_info\x18\x04 \x03(\v2\x14.monitor.ProcessInfoR\vprocessInfo\x127\n" +
	"\fnetwork_info\x18\x05 \x03(\v2\x14.monitor.NetworkInfoR\vnetworkInfo\"\xa3\x01\n" +
	"\bHostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1f\n" +
	"\vkernel_arch\x18\x05 \x01(\tR\n" +
	"kernelArch\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x8e\x01\n" +
	"\aCPUInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1b\n" +
	"\tcores_num\x18\x03 \x01(\x05R\bcoresNum\x12\x18\n" +
	"\apercent\x18\x04 \x01(\x01R\apercent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xba\x01\n" +
	"\n" +
	"MemoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05total\x18\x02 \x01(\tR\x05total\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\tR\tavailable\x12\x12\n" +
	"\x04used\x18\x04 \x01(\tR\x04used\x12\x12\n" +
	"\x04free\x18\x05 \x01(\tR\x04free\x12!\n" +
	"\fuser_percent\x18\x06 \x01(\x01R\vuserPercent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\x90\x01\n" +
	"\vProcessInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x04 \x01(\x01R\n" +
	"memPercent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x8e\x01\n" +
	"\vNetworkInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x04R\tbytesRecv\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xb4\x01\n" +
	"\tAgentInfo\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vkernel_arch\x18\x04 \x01(\tR\n" +
	"kernelArch\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\tR\rlastHeartbeat2\xb6\x03\n" +
	"\x0eMonitorService\x12M\n" +
	"\fInstallAgent\x12\x1c.monitor.InstallAgentRequest\x1a\x1d.monitor.InstallAgentResponse\"\x00\x12P\n" +
	"\rGetSystemInfo\x12\x1d.monitor.GetSystemInfoRequest\x1a\x1e.monitor.GetSystemInfoResponse\"\x00\x12\\\n" +
	"\x11GetLastSystemInfo\x12!.monitor.GetLastSystemInfoRequest\x1a\".monitor.GetLastSystemInfoResponse\"\x00\x12G\n" +
	"\n" +
	"ListAgents\x12\x1a.monitor.ListAgentsRequest\x1a\x1b.monitor.ListAgentsResponse\"\x00\x12\\\n" +
	"\x11CheckServerStatus\x12!.monitor.CheckServerStatusRequest\x1a\".monitor.CheckServerStatusResponse\"\x00B\x16Z\x14monitor-server/protob\x06proto3"

var (
	file_proto_monitor_proto_rawDescOnce sync.Once
	file_proto_monitor_proto_rawDescData []byte
)

func file_proto_monitor_proto_rawDescGZIP() []byte {
	file_proto_monitor_proto_rawDescOnce.Do(func() {
		file_proto_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitor_proto_rawDesc), len(file_proto_monitor_proto_rawDesc)))
	})
	return file_proto_monitor_proto_rawDescData
}

var file_proto_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_monitor_proto_goTypes = []any{
	(*InstallAgentRequest)(nil),       // 0: monitor.InstallAgentRequest
	(*InstallAgentResponse)(nil),      // 1: monitor.InstallAgentResponse
	(*GetSystemInfoRequest)(nil),      // 2: monitor.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),     // 3: monitor.GetSystemInfoResponse
	(*GetLastSystemInfoRequest)(nil),  // 4: monitor.GetLastSystemInfoRequest
	(*GetLastSystemInfoResponse)(nil), // 5: monitor.GetLastSystemInfoResponse
	(*ListAgentsRequest)(nil),         // 6: monitor.ListAgentsRequest
	(*ListAgentsResponse)(nil),        // 7: monitor.ListAgentsResponse
	(*CheckServerStatusRequest)(nil),  // 8: monitor.CheckServerStatusRequest
	(*CheckServerStatusResponse)(nil), // 9: monitor.CheckServerStatusResponse
	(*SystemInfo)(nil),                // 10: monitor.SystemInfo
	(*HostInfo)(nil),                  // 11: monitor.HostInfo
	(*CPUInfo)(nil),                   // 12: monitor.CPUInfo
	(*MemoryInfo)(nil),                // 13: monitor.MemoryInfo
	(*ProcessInfo)(nil),               // 14: monitor.ProcessInfo
	(*NetworkInfo)(nil),               // 15: monitor.NetworkInfo
	(*AgentInfo)(nil),                 // 16: monitor.AgentInfo
}
var file_proto_monitor_proto_depIdxs = []int32{
	10, // 0: monitor.GetSystemInfoResponse.info:type_name -> monitor.SystemInfo
	10, // 1: monitor.GetLastSystemInfoResponse.info:type_name -> monitor.SystemInfo
	16, // 2: monitor.ListAgentsResponse.agents:type_name -> monitor.AgentInfo
	11, // 3: monitor.SystemInfo.host_info:type_name -> monitor.HostInfo
	12, // 4: monitor.SystemInfo.cpu_info:type_name -> monitor.CPUInfo
	13, // 5: monitor.SystemInfo.memory_info:type_name -> monitor.MemoryInfo
	14, // 6: monitor.SystemInfo.process_info:type_name -> monitor.ProcessInfo
	15, // 7: monitor.SystemInfo.network_info:type_name -> monitor.NetworkInfo
	0,  // 8: monitor.MonitorService.InstallAgent:input_type -> monitor.InstallAgentRequest
	2,  // 9: monitor.MonitorService.GetSystemInfo:input_type -> monitor.GetSystemInfoRequest
	4,  // 10: monitor.MonitorService.GetLastSystemInfo:input_type -> monitor.GetLastSystemInfoRequest
	6,  // 11: monitor.MonitorService.ListAgents:input_type -> monitor.ListAgentsRequest
	8,  // 12: monitor.MonitorService.CheckServerStatus:input_type -> monitor.CheckServerStatusRequest
	1,  // 13: monitor.MonitorService.InstallAgent:output_type -> monitor.InstallAgentResponse
	3,  // 14: monitor.MonitorService.GetSystemInfo:output_type -> monitor.GetSystemInfoResponse
	5,  // 15: monitor.MonitorService.GetLastSystemInfo:output_type -> monitor.GetLastSystemInfoResponse
	7,  // 16: monitor.MonitorService.ListAgents:output_type -> monitor.ListAgentsResponse
	9,  // 17: monitor.MonitorService.CheckServerStatus:output_type -> monitor.CheckServerStatusResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_monitor_proto_init() }
func file_proto_monitor_proto_init() {
	if File_proto_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_proto_rawDesc), len(file_proto_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitor_proto_goTypes,
		DependencyIndexes: file_proto_monitor_proto_depIdxs,
		MessageInfos:      file_proto_monitor_proto_msgTypes,
	}.Build()
	File_proto_monitor_proto = out.File
	file_proto_monitor_proto_goTypes = nil
	file_proto_monitor_proto_depIdxs = nil
}
